### PR TITLE
refactor: migrate to `useStepper`

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Stepper logic simplication

## How this PR fixes it

A new `useStepper` hook replaces the `StepperFactory`, simplifying the state of all flows.

## How to test

Navigate through the education series, claiming and delegation steppers and observe no change in behaviour.

### CODE REVIEW

**Review by katspaugh — APPROVED** [review]
👍

**Comment by francovenica** [comment]
Question, is the line that was at the top to showcase how far into the steps you were was removed on purpose?

This is how it looks in prod:
image

**Comment by iamacook** [comment]
> Question, is the line that was at the top to showcase how far into the steps you were was removed on purpose?

Apologies, that was an oversight. I've added it back (f14549b).

**Comment by francovenica** [comment]
The progress bar is visible now

I've imported the PR url as a custom app in Prod so I can use the claim part of the app. 
The educational part, redelegation and claiming steppers are working fine

**Pull request merged**
